### ISSUE TITLE
JS to Java serialization is slow.

### ISSUE THREAD

**Issue by Lomilar** [Eduworks/ew#13]
at jdk.nashorn.internal.runtime.arrays.ArrayData.computeIteratorKeys(ArrayData.java:786)
	at jdk.nashorn.internal.runtime.arrays.ArrayData.indexIterator(ArrayData.java:803)
	at jdk.nashorn.internal.runtime.ScriptObject.getOwnKeys(ScriptObject.java:1348)
	at jdk.nashorn.internal.runtime.ScriptObject$ValueIterator.init(ScriptObject.java:2486)
	at jdk.nashorn.internal.runtime.ScriptObject$ScriptObjectIterator.hasNext(ScriptObject.java:2441)
	at jdk.nashorn.api.scripting.ScriptObjectMirror$22.call(ScriptObjectMirror.java:487)
	at jdk.nashorn.api.scripting.ScriptObjectMirror$22.call(ScriptObjectMirror.java:482)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.inGlobal(ScriptObjectMirror.java:858)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.values(ScriptObjectMirror.java:482)
	at com.eduworks.resolver.lang.LevrJsParser.jsToJava(LevrJsParser.java:240)
	at com.eduworks.resolver.lang.LevrJsParser.jsToJava(LevrJsParser.java:230)

This is the stack of very slow operations.

**Comment by Lomilar** [comment]
2d6e0701ba118d025e05e5f83e9d4c3826b5053c (mis-typed commit)
